# Generated by Django 4.2.18 on 2025-02-11 07:12

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the component', primary_key=True, serialize=False)),
                ('classification', models.CharField(help_text='Hierarchical classification following EuroTempl naming convention', max_length=50, validators=[django.core.validators.RegexValidator(message='Classification must follow EuroTempl format: ET_XXX_XXXX_XXX_000', regex='^ET_[A-Z]{3}_[A-Z]{4}_[A-Z]{3}_\\d{3}(_[rv]\\d+)?$')])),
                ('name', models.CharField(help_text='Verb-noun pair describing component purpose', max_length=100)),
                ('version', models.CharField(help_text='Component version following semantic versioning', max_length=20)),
                ('functional_properties', models.JSONField(default=dict, help_text='Stores acoustic, EMI, and other functional characteristics')),
                ('base_geometry', django.contrib.gis.db.models.fields.GeometryField(dim=3, help_text='Base geometric definition using PostGIS', srid=4326)),
                ('core_mission', models.CharField(help_text='Single core mission as per EuroTempl principles', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if component is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'et_component',
                'indexes': [models.Index(fields=['classification'], name='et_componen_classif_c5acb2_idx'), models.Index(fields=['name'], name='et_componen_name_1f6436_idx'), models.Index(fields=['is_active'], name='et_componen_is_acti_f8db76_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('classification', 'version'), name='unique_component_version'),
        ),
    ]
