# Generated by Django 4.2.18 on 2025-02-11 08:02

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parameter_materialrequirement_documentation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentinstance',
            options={},
        ),
        migrations.RemoveField(
            model_name='componentinstance',
            name='location',
        ),
        migrations.RemoveField(
            model_name='componentinstance',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='componentinstance',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='instance_properties',
            field=models.JSONField(default=dict, help_text='Flexible instance-specific properties'),
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='internal_id',
            field=models.IntegerField(db_index=True, default=1, help_text='Internal sequential identifier for performance optimization', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='When instance was last modified'),
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='spatial_bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(help_text='Spatial bounding box for quick filtering', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='spatial_data',
            field=django.contrib.gis.db.models.fields.GeometryField(dim=3, help_text='3D geometric representation with SFCGAL support', srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='status',
            field=models.CharField(choices=[('planned', 'PLANNED'), ('in_progress', 'IN_PROGRESS'), ('complete', 'COMPLETE'), ('obsolete', 'OBSOLETE')], default='planned', help_text='Current status in lifecycle', max_length=20),
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='status_changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When status was last changed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number of the instance', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='component',
            field=models.ForeignKey(help_text='Reference to parent Component', on_delete=django.db.models.deletion.RESTRICT, to='core.component'),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When instance was created'),
        ),
            # First add UUID field without making it primary key
        migrations.AddField(
            model_name='componentinstance',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        # Copy data and set up new ID
        migrations.RunPython(
            code=lambda apps, schema_editor: schema_editor.execute(
                'UPDATE core_componentinstance SET uuid_id = gen_random_uuid();'
            )
        ),
        # Remove old ID and make UUID primary
        migrations.RemoveField(
            model_name='componentinstance',
            name='id',
        ),
        migrations.RenameField(
            model_name='componentinstance',
            old_name='uuid_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='id',
        field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name='componentinstance',
            index=models.Index(fields=['internal_id'], name='et_componen_interna_5cc626_idx'),
        ),
        migrations.AddIndex(
            model_name='componentinstance',
            index=models.Index(fields=['status'], name='et_componen_status_719023_idx'),
        ),
        migrations.AddIndex(
            model_name='componentinstance',
            index=models.Index(fields=['component'], name='et_componen_compone_eba965_idx'),
        ),
        migrations.AddIndex(
            model_name='componentinstance',
            index=models.Index(fields=['created_at'], name='et_componen_created_0c013d_idx'),
        ),
        migrations.AlterModelTable(
            name='componentinstance',
            table='et_component_instance',
        ),
    ]
