# Generated by Django 4.2.18 on 2025-02-11 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_componentinstance_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parametervalue',
            name='unique_parameter_value_per_instance',
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='modified_by',
            field=models.ForeignKey(help_text='User who last modified the value', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the value was recorded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='validation_status',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('pending', 'Pending Validation')], default='pending', help_text='Current validation status', max_length=50),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='instance',
            field=models.ForeignKey(help_text='Reference to the component instance', on_delete=django.db.models.deletion.CASCADE, to='core.componentinstance'),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='parameter',
            field=models.ForeignKey(help_text='Reference to the parameter definition', on_delete=django.db.models.deletion.CASCADE, to='core.parameter'),
        ),
        migrations.AddIndex(
            model_name='parametervalue',
            index=models.Index(fields=['validation_status'], name='et_paramete_validat_cb98a4_idx'),
        ),
        migrations.AddIndex(
            model_name='parametervalue',
            index=models.Index(fields=['recorded_at'], name='et_paramete_recorde_dccf6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.UniqueConstraint(fields=('instance', 'parameter'), name='unique_parameter_per_instance'),
        ),
    ]
