# Generated by Django 4.2.18 on 2025-02-11 12:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_parametervalue_unique_parameter_value_per_instance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the connection', primary_key=True, serialize=False)),
                ('connection_type', models.CharField(choices=[('bolted', 'BOLTED'), ('slotted', 'SLOTTED'), ('welded', 'WELDED'), ('screwed', 'SCREWED'), ('adhesive', 'ADHESIVE')], help_text='Classification of connection type', max_length=50)),
                ('connection_properties', models.JSONField(default=dict, help_text='Detailed specifications including fastener details, EMI shielding')),
                ('spatial_relationship', django.contrib.gis.db.models.fields.GeometryField(dim=3, help_text='3D geometric representation of connection', srid=4326)),
                ('spatial_bbox', django.contrib.gis.db.models.fields.PolygonField(help_text='Spatial bounding box for quick filtering', null=True, srid=4326)),
                ('is_structural', models.BooleanField(default=False, help_text='Indicates if connection is load-bearing')),
                ('status', models.CharField(choices=[('planned', 'PLANNED'), ('in_progress', 'IN_PROGRESS'), ('complete', 'COMPLETE'), ('obsolete', 'OBSOLETE')], default='planned', help_text='Current lifecycle status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('status_changed_at', models.DateTimeField(auto_now_add=True, help_text='When status was last changed')),
                ('instance_1', models.ForeignKey(help_text='First connected instance', on_delete=django.db.models.deletion.RESTRICT, related_name='connections_as_first', to='core.componentinstance')),
                ('instance_2', models.ForeignKey(help_text='Second connected instance', on_delete=django.db.models.deletion.RESTRICT, related_name='connections_as_second', to='core.componentinstance')),
                ('parent_connection', models.ForeignKey(blank=True, help_text='Reference to parent connection in hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.connection')),
            ],
            options={
                'db_table': 'et_connection',
                'indexes': [models.Index(fields=['connection_type'], name='et_connecti_connect_44862a_idx'), models.Index(fields=['status'], name='et_connecti_status_7b5011_idx'), models.Index(fields=['is_structural'], name='et_connecti_is_stru_d8877a_idx'), models.Index(fields=['created_at'], name='et_connecti_created_9b46ce_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.CheckConstraint(check=models.Q(('instance_1__lt', models.F('instance_2'))), name='prevent_duplicate_connections'),
        ),
    ]
